#!/usr/bin/env python3

import random
import sys
import time

print("test0 starting")
time.sleep(random.random() * 5)
print("test0 message:", sys.argv[1])
print("test0 done")
if random.random() < 0.5:
    print("test0 failed")
    raise SystemExit(1)
else:
    print("test0 succeeded")
    raise SystemExit(0)

