#!/usr/bin/env python3

import logging
import random
import sys
import time

logging.basicConfig(level=logging.INFO)

logging.info("test0 starting")
time.sleep(random.random() * 30)
logging.info(f"test0 message: {sys.argv[1]}")
logging.info("test0 done")
if random.random() < 0.5:
    logging.info("test0 failed")
    raise SystemExit(1)
else:
    logging.info("test0 succeeded")
    raise SystemExit(0)

