name: Apsis CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upgrade pip
      run: pip3 install --upgrade pip 'setuptools>=61'

    - name: Install package
      run: pip3 install -e .[dev]

    - name: Install procstar
      run: curl -S https://github.com/alexhsamuel/procstar/releases/download/v$(python -c 'import procstar; print(procstar.__version__)')/procstar --output-dir /usr/local/bin/

    - name: Run Python unit tets
      run: pytest test/unit -m "not local_ssh"

    - name: Run Python integration tets
      run: pytest test/int -m "not local_ssh"

